#!/bin/bash

echo SPAWNING SWARM

start_new_drone() {
    osascript -e 'tell app "Terminal"
        do script "/Users/brandonkynoch/desktop/projects/drone/drone/output"
    end tell'
}

make clean
make

for i in {1..12}
do
    start_new_drone &
done

wait
echo "done"