#define TRUE 1
#define FALSE 0
#define bool int
#define ASSERT assert

#define NETWORK_STD_MSG_LEN 1024
#define IS_SIMULATION TRUE

#define SIMULATION_SERVER_SOCKET 1755
#define DRONE_SERVER_SOCKET 8060

// DRONE CONSTS
#define DRONE_SENSOR_COUNT 8

#define DRONE_SENSOR_RANGE 2.0